- name: Wait for instances to finish booting
  connection: local
  become: no
  wait_for:
    host="{{ansible_ssh_host|default(inventory_hostname)}}"
    search_regex=OpenSSH
    port=22
    delay=30
    timeout=600

- name: Gather facts now that we know the instances are ready
  setup:
    filter: "ansible_*"

#- name: debug stuff
#  vars:
#    msg: |
#           HOST Variables ("hostvars"):
#           --------------------------------
#           {{ hostvars | to_nice_json }}
#  debug:
#    msg: "{{ msg.split('\n') }}"

- name: build hosts file
  lineinfile: dest=/etc/hosts regexp='^{{ hostvars[item].ansible_default_ipv4.address }}.*$' line="{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].ansible_hostname }} {{ hostvars[item].ansible_nodename }}" state=present
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: "{{ groups['cluster'] }}"

- name: disable selinux
  selinux: state=disabled

- name: disable of selinux - now
  command: setenforce 0

- name: Ensure net.bridge.bridge-nf-call-iptables is set. See kubeadm
  copy: src=k8s.conf owner=root group=root dest=/etc/sysctl.d/k8s.conf

- name: Run sysctl
  command: sysctl --system

- name: Add Kubernetes yum repo
  yum_repository:
    name: kubernetes
    description: Kubernetes kubeadm
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg
    gpgcheck: yes

- name: install utility programs
  yum:
    disable_gpg_check: yes
    state: present
    name:
      - wget
      - ntp
      - screen
      - epel-release
      - vim
      - iptables
      - iptables-utils
      - iptables-services
      - ncurses-term
      - kubelet
      - kubeadm
      - kubectl
      - kernel-devel
      - kernel-headers

- name: install epel utility programs
  yum:
    state: present
    disable_gpg_check: yes
    name:
      - jq
      - lvm2
      - yum-utils
      - device-mapper-persistent-data

- name: remove all old docker packages
  yum:
    state: removed
    disable_gpg_check: yes
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine

- name: install docker ce yum repo
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: install docker ce
  yum: name=docker-ce state=present disable_gpg_check=yes

- name: enable kube services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - docker
    - ntpd
    - kubelet

- name: download crictl
  get_url:
    url: https://github.com/kubernetes-incubator/cri-tools/releases/download/v1.0.0-beta.0/crictl-v1.0.0-beta.0-linux-amd64.tar.gz
    dest: /home/centos/crictl.tar.gz

- name: install crictl
  unarchive:
    src: /home/centos/crictl.tar.gz
    remote_src: yes
    dest: /bin

- name: turn off swap
  command: swapoff -a

- name: remove swap from /etc/fstab
  lineinfile:
    path: /etc/fstab
    state: absent
    regexp: "swap"


